# Generated by Django 3.2.3 on 2021-05-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'Consulta'], [1, 'Reclamo'], [2, 'Sugerencia'], [3, 'Felicitaciones'], [4, 'Solicitud de registro']])),
                ('mensaje', models.TextField()),
                ('avisos', models.BooleanField()),
                ('rut', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('nombre', models.TextField()),
                ('telefono', models.IntegerField()),
                ('rubro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=300)),
                ('precio', models.IntegerField()),
                ('vencimiento', models.DateField()),
                ('stock', models.IntegerField()),
                ('stock_critico', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.familia')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('nombre', models.TextField()),
                ('telefono', models.IntegerField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cargo')),
            ],
        ),
    ]
