# Generated by Django 3.2.3 on 2021-07-21 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordencompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(blank=True, null=True, upload_to='')),
                ('estado', models.BigIntegerField(choices=[[0, 'Pendiente'], [1, 'Aprobada'], [2, 'Rechazada']], default=0, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
        ),
    ]
