# Generated by Django 3.2.3 on 2021-07-20 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='factura',
        ),
    ]
