# Generated by Django 3.2.3 on 2021-07-14 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='descripcio',
            new_name='descripcion',
        ),
    ]
