# Generated by Django 3.2.3 on 2021-07-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario')),
                ('rut', models.IntegerField(unique=True, verbose_name='Run')),
                ('correo', models.CharField(max_length=300, unique=True, verbose_name='Correo')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('telefono', models.IntegerField(unique=True, verbose_name='Telefono')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
