# Generated by Django 3.2.3 on 2021-07-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(default='Sexoo', max_length=150, verbose_name='Cargo'),
        ),
    ]
