# Generated by Django 3.2.3 on 2021-07-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(default='Cliente', max_length=150, verbose_name='Cargo'),
        ),
    ]
