# Generated by Django 3.2.3 on 2021-07-14 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210713_2118'),
        ('usuario', '0004_alter_usuario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo'),
        ),
    ]
