# Generated by Django 3.2.3 on 2021-05-23 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conacto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='conacto',
            new_name='contacto',
        ),
    ]
