//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWFF.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA
    {
        public BOLETA()
        {
            this.DESPACHO = new HashSet<DESPACHO>();
        }
    
        public decimal ID_BOLETA { get; set; }
        public decimal ORDEN_COMPRA_ID_ORDEN_COMPRA { get; set; }
        public Nullable<decimal> ID_CLIENTE { get; set; }
        public Nullable<decimal> ID_PRODUCO { get; set; }
        public string NOMBRE_PRODUCTO { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public Nullable<decimal> MONTO_TOTAL { get; set; }
    
        public virtual ORDEN_COMPRA ORDEN_COMPRA { get; set; }
        public virtual ICollection<DESPACHO> DESPACHO { get; set; }
    }
}
