//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWFF.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARGO_JN
    {
        public string JN_OPERATION { get; set; }
        public string JN_ORACLE_USER { get; set; }
        public System.DateTime JN_DATETIME { get; set; }
        public string JN_NOTES { get; set; }
        public string JN_APPLN { get; set; }
        public Nullable<decimal> JN_SESSION { get; set; }
        public string ID_CARGO { get; set; }
        public string NOM_CARGO { get; set; }
        public string DESCRIPCION_CARGO { get; set; }
        public decimal EMPLEADO_ID_EMPLEADO { get; set; }
        public string EMPLEADO_RUT1 { get; set; }
    }
}
