//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWFF.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.COTIZACION = new HashSet<COTIZACION>();
            this.ORDEN_DESPACHO = new HashSet<ORDEN_DESPACHO>();
        }
    
        public decimal ID_CLIENTE { get; set; }
        public string CORREO { get; set; }
        public string CONTRASEÑA { get; set; }
        public string ID_PERSONA { get; set; }
        public string PERSONA_RUT { get; set; }
        public string COMUNA_ID_COMUNA { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        public virtual ICollection<COTIZACION> COTIZACION { get; set; }
        public virtual ICollection<ORDEN_DESPACHO> ORDEN_DESPACHO { get; set; }
    }
}
