//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWFF.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class COTIZACION
    {
        public COTIZACION()
        {
            this.ORDEN_COMPRA = new HashSet<ORDEN_COMPRA>();
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public decimal ID_COTIZACION { get; set; }
        public System.DateTime FECHA_COTIZACION { get; set; }
        public decimal TOTAL_COTIZACION { get; set; }
        public decimal EMPLEADO_CARGO_ID { get; set; }
        public decimal PROVEEDOR_ID { get; set; }
        public decimal CLIENTE_RUT { get; set; }
        public decimal EMPLEADO_ID { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual ICollection<ORDEN_COMPRA> ORDEN_COMPRA { get; set; }
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
