//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWFF.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class COTIZACION_JN
    {
        public string JN_OPERATION { get; set; }
        public string JN_ORACLE_USER { get; set; }
        public System.DateTime JN_DATETIME { get; set; }
        public string JN_NOTES { get; set; }
        public string JN_APPLN { get; set; }
        public Nullable<decimal> JN_SESSION { get; set; }
        public decimal ID_COTIZACION { get; set; }
        public Nullable<decimal> ID_EMPLEADO { get; set; }
        public Nullable<decimal> ID_PROVEEDOR { get; set; }
        public Nullable<decimal> ID_PRODUCTO { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<System.DateTime> FECHA_PEDIDO { get; set; }
        public Nullable<decimal> MONTO_TOTAL { get; set; }
        public decimal EMPLEADO_ID_EMPLEADO { get; set; }
        public string EMPLEADO_RUT1 { get; set; }
        public decimal CLIENTE_ID_CLIENTE { get; set; }
        public string CLIENTE_RUT { get; set; }
        public string CLIENTE_COMUNA_ID_COMUNA { get; set; }
    }
}
