//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWFF.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESPACHO
    {
        public DESPACHO()
        {
            this.ORDENDESPACHO = new HashSet<ORDENDESPACHO>();
        }
    
        public decimal ID_DESPACHO { get; set; }
        public System.DateTime FECHA_DESPACHO { get; set; }
        public string ESTADO_DESPACHO { get; set; }
        public decimal FACTURA_ID_FACTURA { get; set; }
        public decimal BOLETA_ID_BOLETA { get; set; }
    
        public virtual BOLETA BOLETA { get; set; }
        public virtual FACTURA FACTURA { get; set; }
        public virtual ICollection<ORDENDESPACHO> ORDENDESPACHO { get; set; }
    }
}
