//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWFF.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECCIONES
    {
        public decimal PERSONA_RUT_PERSONA { get; set; }
        public decimal COMUNA_ID_COMUNA { get; set; }
        public decimal COMUNA_ID_REGION { get; set; }
        public decimal ID_DIRECCION { get; set; }
        public string DIRECCION { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
