//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWFF.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public EMPLEADO()
        {
            this.CARGO = new HashSet<CARGO>();
            this.COTIZACION = new HashSet<COTIZACION>();
        }
    
        public decimal ID_EMPLEADO { get; set; }
        public Nullable<decimal> RUT { get; set; }
        public Nullable<decimal> ID_CARGO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string PERSONA_RUT { get; set; }
    
        public virtual ICollection<CARGO> CARGO { get; set; }
        public virtual ICollection<COTIZACION> COTIZACION { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
