//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWFF.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public decimal RUT_PERSONA { get; set; }
        public decimal CARGO_ID_CARGO { get; set; }
        public decimal ID_EMPLEADO { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
