//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWFF.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public FACTURA()
        {
            this.DESPACHO = new HashSet<DESPACHO>();
            this.ORDEN_COMPRA = new HashSet<ORDEN_COMPRA>();
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public decimal ID_FACTURA { get; set; }
        public decimal CANTIDAD_PROD_FACTURA { get; set; }
        public decimal TOTAL_FACTURA { get; set; }
        public System.DateTime FECHA_FACTURA { get; set; }
    
        public virtual ICollection<DESPACHO> DESPACHO { get; set; }
        public virtual ICollection<ORDEN_COMPRA> ORDEN_COMPRA { get; set; }
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
