//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWFF.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FermEntities : DbContext
    {
        public FermEntities()
            : base("name=FermEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BOLETA> BOLETA { get; set; }
        public DbSet<CARGO> CARGO { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<COMUNA> COMUNA { get; set; }
        public DbSet<COTIZACION> COTIZACION { get; set; }
        public DbSet<DESPACHO> DESPACHO { get; set; }
        public DbSet<EMPLEADO> EMPLEADO { get; set; }
        public DbSet<FACTURA> FACTURA { get; set; }
        public DbSet<FAMILIA> FAMILIA { get; set; }
        public DbSet<ORDEN_COMPRA> ORDEN_COMPRA { get; set; }
        public DbSet<ORDEN_DESPACHO> ORDEN_DESPACHO { get; set; }
        public DbSet<PERSONA> PERSONA { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public DbSet<BOLETA_JN> BOLETA_JN { get; set; }
        public DbSet<CARGO_JN> CARGO_JN { get; set; }
        public DbSet<CLIENTE_JN> CLIENTE_JN { get; set; }
        public DbSet<COMUNA_JN> COMUNA_JN { get; set; }
        public DbSet<COTIZACION_JN> COTIZACION_JN { get; set; }
        public DbSet<DESPACHO_JN> DESPACHO_JN { get; set; }
        public DbSet<EMPLEADO_JN> EMPLEADO_JN { get; set; }
        public DbSet<FACTURA_JN> FACTURA_JN { get; set; }
        public DbSet<FAMILIA_JN> FAMILIA_JN { get; set; }
        public DbSet<ORDEN_COMPRA_JN> ORDEN_COMPRA_JN { get; set; }
        public DbSet<ORDEN_DESPACHO_JN> ORDEN_DESPACHO_JN { get; set; }
        public DbSet<PERSONA_JN> PERSONA_JN { get; set; }
        public DbSet<PRODUCTO_JN> PRODUCTO_JN { get; set; }
        public DbSet<PROVEEDOR_JN> PROVEEDOR_JN { get; set; }
    }
}
