//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWFF.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FermeEntities : DbContext
    {
        public FermeEntities()
            : base("name=FermeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BOLETA> BOLETA { get; set; }
        public DbSet<CARGO> CARGO { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<COMUNA> COMUNA { get; set; }
        public DbSet<COTIZACION> COTIZACION { get; set; }
        public DbSet<DESPACHO> DESPACHO { get; set; }
        public DbSet<DIRECCIONES> DIRECCIONES { get; set; }
        public DbSet<EMPLEADO> EMPLEADO { get; set; }
        public DbSet<FACTURA> FACTURA { get; set; }
        public DbSet<ORDEN_COMPRA> ORDEN_COMPRA { get; set; }
        public DbSet<ORDENDESPACHO> ORDENDESPACHO { get; set; }
        public DbSet<PERSONA> PERSONA { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<FAMILIA> Familia { get; set; }
    }
}
