//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWFF.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_DESPACHO
    {
        public ORDEN_DESPACHO()
        {
            this.DESPACHO = new HashSet<DESPACHO>();
        }
    
        public decimal ID_ORDEN_COMPRA { get; set; }
        public decimal CLIENTE_ID_CLIENTE { get; set; }
        public string CLIENTE_RUT { get; set; }
        public string CLIENTE_COMUNA_ID_COMUNA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<DESPACHO> DESPACHO { get; set; }
    }
}
