//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWFF.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_COMPRA
    {
        public decimal ID_ORDEN_COMPRA { get; set; }
        public string ESTADO { get; set; }
        public decimal COTIZACION_ID { get; set; }
        public decimal COTIZACION_PROVEEDOR_ID { get; set; }
        public decimal BOLETA_ID_BOLETA { get; set; }
        public decimal FACTURA_ID_FACTURA { get; set; }
        public decimal COTIZACION_CLIENTE_RUT_PERSONA { get; set; }
    
        public virtual BOLETA BOLETA { get; set; }
        public virtual COTIZACION COTIZACION { get; set; }
        public virtual FACTURA FACTURA { get; set; }
    }
}
