//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWFF.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDENDESPACHO
    {
        public decimal ID_ORDEN_DESPACHO { get; set; }
        public System.DateTime FECHA_ORDEN_DESPACHO { get; set; }
        public decimal DESPACHO_ID_DESPACHO { get; set; }
    
        public virtual DESPACHO DESPACHO { get; set; }
    }
}
