//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWFF.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_COMPRA
    {
        public ORDEN_COMPRA()
        {
            this.BOLETA = new HashSet<BOLETA>();
            this.FACTURA = new HashSet<FACTURA>();
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public decimal ID_ORDEN_COMPRA { get; set; }
        public Nullable<decimal> ID_COTIZACION { get; set; }
        public Nullable<decimal> ID_PRODUCTO { get; set; }
        public string ESTADO { get; set; }
        public decimal COTIZACION_ID_COTIZACION { get; set; }
    
        public virtual ICollection<BOLETA> BOLETA { get; set; }
        public virtual COTIZACION COTIZACION { get; set; }
        public virtual ICollection<FACTURA> FACTURA { get; set; }
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
