//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWFF.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA_JN
    {
        public string JN_OPERATION { get; set; }
        public string JN_ORACLE_USER { get; set; }
        public System.DateTime JN_DATETIME { get; set; }
        public string JN_NOTES { get; set; }
        public string JN_APPLN { get; set; }
        public Nullable<decimal> JN_SESSION { get; set; }
        public string RUT { get; set; }
        public string NOMBRE { get; set; }
        public string CORREO { get; set; }
        public Nullable<int> TELEFONO { get; set; }
        public string DIRECCION { get; set; }
        public string ID_COMUNA { get; set; }
    }
}
