//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWFF.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public PERSONA()
        {
            this.DIRECCIONES = new HashSet<DIRECCIONES>();
        }
    
        public decimal RUT_PERSONA { get; set; }
        public string NOMBRE_PERSONA { get; set; }
        public string CORREO_PERSONA { get; set; }
        public decimal TELEFONO_PERSONA { get; set; }
        public string CONTRASENA_PERSONA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<DIRECCIONES> DIRECCIONES { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
