//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWFF.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_JN
    {
        public string JN_OPERATION { get; set; }
        public string JN_ORACLE_USER { get; set; }
        public System.DateTime JN_DATETIME { get; set; }
        public string JN_NOTES { get; set; }
        public string JN_APPLN { get; set; }
        public Nullable<decimal> JN_SESSION { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public Nullable<decimal> ID_FAMILIA { get; set; }
        public Nullable<decimal> ID_PROVEEDOR { get; set; }
        public string NOM_PRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> PRECIO_VENTA { get; set; }
        public Nullable<decimal> PRECIO_COMPRA { get; set; }
        public Nullable<System.DateTime> FECHA_VENC { get; set; }
        public Nullable<decimal> STOCK { get; set; }
        public Nullable<decimal> STOCK_CRITICO { get; set; }
        public decimal PROVEEDOR_ID_NOM_PROVEEDOR { get; set; }
        public decimal FAMILIA_ID_FAMILIA { get; set; }
        public decimal ORDEN_COMPRA_ID_ORDEN_COMPRA { get; set; }
    }
}
