//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWFF.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.BOLETA = new HashSet<BOLETA>();
            this.COTIZACION = new HashSet<COTIZACION>();
            this.FACTURA = new HashSet<FACTURA>();
        }
    
        public decimal ID_PRODUCTO { get; set; }
        public string NOMBRE_PRODUCTO { get; set; }
        public string DESCRIPCION_PRODUCTO { get; set; }
        public decimal PRECIO_PRODUCTO { get; set; }
        public Nullable<System.DateTime> FECHA_VENCIMIENTO { get; set; }
        public decimal STOCK_PRODUCTO { get; set; }
        public Nullable<decimal> STOCK_CRITICO_PRODUCTO { get; set; }
        public decimal PROVEEDOR_ID_PROVEEDOR { get; set; }
    
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual ICollection<BOLETA> BOLETA { get; set; }
        public virtual ICollection<COTIZACION> COTIZACION { get; set; }
        public virtual ICollection<FACTURA> FACTURA { get; set; }
    }
}
