//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWFF.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public PROVEEDOR()
        {
            this.COTIZACION = new HashSet<COTIZACION>();
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public decimal ID_PROVEEDOR { get; set; }
        public string NOMBRE_PROVEEDOR { get; set; }
        public decimal TELEFONO_PROVEEDOR { get; set; }
        public string RUBRO_PROVEEDOR { get; set; }
    
        public virtual ICollection<COTIZACION> COTIZACION { get; set; }
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
